### PR TITLE
Add `resolve` config-options to allow fully customizable

### PR DESCRIPTION
**Pull request by lwr**
As changes to README, we can now custom the way how module paths resolves via the `resolve` option: 

 ```js
 Tarp.require({main: "./scripts/main", resolve: id => `/path/to/node/modules/${id}.js`});
 ```

### CODE REVIEW

**Comment by letorbi** [comment]
Hi @lwr, thanks for the PR, but I'm not 100% sure what you want to achieve with it. If I've interpreted your code-changes right, you want to add an option to override the way how Tarp.require resolves module paths.

Can you explain to me, why just changing the `paths` array is not enough and you need such an option?

**Comment by lwr** [comment]
@letorbi

Actually we need something like alias, but it is not valueable to add it to a liweight project like this

A custom resolver is much more powerful to meets vary requirements by adding only few bytes of code

That is what this PR for

**Comment by letorbi** [comment]
I've merged your PR, but changed its actual implementation slightly. The functionality should be the same, so please file an issue if it's not.

**Comment by lwr** [comment]
@letorbi I have read 9f9c146d52bf30199d2e63c1ab827f1db21df965

I don't think it is a good design that pass to custom resolver for all module paths.

It should be better that custom loader only be used to resolve the absolute id (no relative)

That's why I test `matches[2]` (dotted implies id is relative) before pass it to config.resolve.

Anyway, it it is implemented in this way, we should have a way to access the default resolver, maybe you could put it to the Tarp namespace

so the usage code would looks like
```js
const myAlias = {module1, module2};

Tarp.require({resolve: (id, pwd) => {
    if (myAlias.hasOwnProperty(id)) {
        return myAlias[id];
    } else {
        return Tarp.defaultResolve(id, pwd);
    }
}})
```

from my specification, it looks like
```js
const myAlias = {module1, module2};

Tarp.require({resolve: id => {
    if (myAlias.hasOwnProperty(id)) {
        return myAlias[id];
    } // if return undefined / null / empty, fall back using default resolver
}})
```

**Comment by letorbi** [comment]
I decided to allow the replacement of the whole path-resolving logic, because I wanted to make the resolve override as flexible as possible. But you are right, I might be handy for other developers to have access to the default resolver, so I've added a way to access it from a custom resolver.

I didn't choose the way you proposed, because I don't want to pollute the `Tarp` namespace. Instead the default path-resolver is passed to the custom path-resolver as a third parameter. So your custom-resolver example looks a bit different:

```
Tarp.require({resolve: (id, pwd, defaultResolver) => {
    if (myAlias.hasOwnProperty(id)) {
        return myAlias[id];
    } else {
        return defaultResolve(id, pwd);
    }
}})
```

I hope this fits your needs. The changes are already in the *master* branch and if I don't hear anything from you I will update the NPM package tomorrow.

Thanks again for the PR and the feedback :)

**Pull request merged**
